# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a621d306826a93c875f2790ab5122ac9e2c5ab0d3d9d3876160a2c8c2217899effb2a9da4ff453bbc14333a0a81286dd4f7a43e7d9169676a46c1c2e9e504d9d

test:
  secret_key_base: fee0581638837a069869b26eef00edbd5fbe8e35f7afd887dc77113192efac7e7836c6bb0cd3c8e4c33dfd1bc6c0b0d0bfd7c12dd939ab35193719aa8cfda7bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
